### ISSUE TITLE
is there a way to avoid automatic new window creation?

### ISSUE THREAD

**Issue by roolio** [kidanger/vpv#63]
Hello, I'd like to launch 2 directories on the same view (to switch with space) knowing that "nw" is the default behavior : 

```shell
./vpv T1/ T2/
```
 is equivalent to 

```shell
./vpv T1/ nw T2/
```

is equivalent to 

```shell
./vpv aw T1/ T2/
```

So what's the way to avoid new window creation ? 

(btw, I've tested features in the dev branch : aws s3 loading and the fuzzy file finder : that's awesome ! are all the gdal vsi "drivers" accepted, or just S3? )

**Comment by kidanger** [comment]
Hello,
Since `aw` is by default, you need to toggle it back off, so
```
vpv aw T1 T2
```
will put the two sequences in the same window.

Another example, with one window containing T1, and another containing T2 and T3:
```
vpv T1 aw T2 T3
```

I almost never use this "multiple sequences in a window" feature, instead I use the fullscreen layout and switch between windows with tab/shift-tab or 1,2,3,...

About gdal vsi,
- http(s):// is replaced by /vsicurl/http(s)://
- s3:// is replaced by /vsis3/
- if the path starts with /vsis3/ and ends with /, then vpv will do a recursive listing
- if the path ends with .zip, then vpv will do a recursive listing
for example: `vpv https://www.ssec.wisc.edu/hanis/examples/zipex/michael.zip`

So the support is mostly around zip and S3. You should be able to use `vpv /vsigs/.../someimage.tif` but the recursive listing would require some changes to vpv.
Let me know if you have some ideas around other vsi drivers.

**Comment by roolio** [comment]
got it, thanks.

My use case for loading in the same window is to have 2 versions of the same pictures at different resolutions : 
you browse quickly with the low res, and if you spot something, you switch to high res.

Cheers
